apiVersion: batch/v1
kind: Job
metadata:
  name: configure-aiops-network-policy
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  namespace: {{.Values.spec.eventManager.namespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "96Mi"
              cpu: "300m"
          command:
            - /bin/sh
            - -c
            - |
              set -eo pipefail
              set -x

              default_policy=$(oc get namespace default -o jsonpath={.metadata.labels.'network\.openshift\.io/policy-group'}) \
              || {
                echo "ERROR: Unable to get default ingress policy ."
                exit 1
              }
              if [ "${default_policy}" == "ingress" ]; then
                echo "INFO: Default network policy is already \"ingress\"."
                exit
              else
                strategy=$(oc get ingresscontroller default \
                  -n openshift-ingress-operator \
                  -o jsonpath={.status.endpointPublishingStrategy.type}) \
                  || {
                    echo "ERROR: Getting ingress controller strategy failed."
                    exit 1
                  }
                if [ "${strategy}" == "HostNetwork" ]; then
                  oc patch namespace default \
                    --type=json \
                    -p '[{"op":"add","path":"/metadata/labels","value":{"network.openshift.io/policy-group":"ingress"}}]' \
                  && echo "INFO: Default network policy set to \"ingress\"." \
                  || {
                    echo "ERROR: Patching network policy labels failed."
                    exit 1
                  }
                fi
              fi

      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin-noi
  backoffLimit: 1