{{- if .Values.spec.isSNO  }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "75"
  name: redis-resource-locker
  namespace: resource-locker-operator
spec:
  patches:
  - id: redis-sen-locker
    patchTemplate: |
      spec:
        size: 2
        members:
          affinity:
            podAntiAffinity: null
    patchType: application/merge-patch+json
    targetObjectRef:
      apiVersion: redis.databases.cloud.ibm.com/v1
      kind: RedisSentinel
      name: example-redis
      namespace: {{.Values.spec.aiManager.namespace}}
  - id: redis-sts-locker
    patchTemplate: |
      spec:
        replicas: 0
        template:
          spec:
            affinity:
              podAntiAffinity: null
    patchType: application/merge-patch+json
    targetObjectRef:
      apiVersion: apps/v1
      kind: StatefulSet
      name: c-example-redis-m
      namespace: {{.Values.spec.aiManager.namespace}}
  serviceAccountRef:
    name: resource-locker-operator-controller-manager
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "76"
  name: redis2-resource-locker
  namespace: resource-locker-operator
spec:
  patches:
  - id: redis-sts-locker
    patchTemplate: |
      spec:
        replicas: 2
    patchType: application/merge-patch+json
    targetObjectRef:
      apiVersion: apps/v1
      kind: StatefulSet
      name: c-example-redis-m
      namespace: {{.Values.spec.aiManager.namespace}}
  serviceAccountRef:
    name: resource-locker-operator-controller-manager

{{- end }}
