apiVersion: orchestrator.aiops.ibm.com/v1alpha1
kind: Installation
metadata:
  name: {{.Values.spec.aiManager.instanceName}}
  namespace: {{.Values.spec.aiManager.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "80"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  size: {{.Values.spec.aiManager.size}}
  storageClass: {{.Values.spec.storageClass}}
  storageClassLargeBlock: {{.Values.spec.storageClassLargeBlock}}
  license:
    accept: true
  #{{- if not .Values.globalImagePullSecrets }}
  #imagePullSecret: ibm-entitlement-key
  #{{- end }}
  pakModules:
    - name: aiopsFoundation
      enabled: {{.Values.spec.aiManager.pakModules.aiopsFoundation.enabled}}
    - name: applicationManager
      enabled: {{.Values.spec.aiManager.pakModules.applicationManager.enabled}}
    - name: aiManager
      enabled: {{.Values.spec.aiManager.pakModules.aiManager.enabled}}
    - name: connection
      enabled: {{.Values.spec.aiManager.pakModules.connection.enabled}}