apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: openshift-cluster-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      name: openshift-cluster-kubeconfig
      namespace: crossplane-system
      key: credentials