apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane-provider-helm
  namespace: upbound-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crossplane-provider-helm
  template:
    metadata:
      name: provider-helm
      namespace: upbound-system
      labels: 
        app: crossplane-provider-helm
    spec:
      containers:
      - image: crossplane/provider-helm-controller:v0.8.0-rc.10.gfee38cf
        name: provider-helm
      serviceAccount: crossplane
      serviceAccountName: crossplane
