apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: iaf-resource-locker
  namespace: resource-locker-operator
spec:
  patches:
  - id: nginx-locker
    patchTemplate: |
      spec:
        replicas: {{.Values.res.nginx.replicas}}
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: apps/v1
      kind: Deployment
      name: ibm-nginx
      namespace: {{.Values.aiManager.namespace}}
  - id: usermgmt-locker
    patchTemplate: |
      spec:
        replicas: {{.Values.res.usermgmt.replicas}}
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: apps/v1
      kind: Deployment
      name: usermgmt
      namespace: {{.Values.aiManager.namespace}}
  - id: zen-core-locker
    patchTemplate: |
      spec:
        replicas: {{.Values.res.zencore.replicas}}
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: apps/v1
      kind: Deployment
      name: zen-core
      namespace: {{.Values.aiManager.namespace}}
  - id: zen-core-api-locker
    patchTemplate: |
      spec:
        replicas: {{.Values.res.zencoreapi.replicas}}
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: apps/v1
      kind: Deployment
      name: zen-core-api
      namespace: {{.Values.aiManager.namespace}}
  - id: automationbase-locker
    patchTemplate: |
      spec:
        kafka:
          entityOperator:
            tlsSidecar:
              resources:
                limits:
                  cpu: "{{.Values.res.kafka.entityOperator.tlsSidecar.limits.cpu}}"
                  memory: "{{.Values.res.kafka.entityOperator.tlsSidecar.limits.memory}}"
                requests:
                  cpu: "{{.Values.res.kafka.entityOperator.tlsSidecar.requests.cpu}}"
                  memory: "{{.Values.res.kafka.entityOperator.tlsSidecar.requests.memory}}"
            topicOperator:
              resources:
                limits:
                  cpu: "{{.Values.res.kafka.entityOperator.topicOperator.limits.cpu}}"
                  memory: "{{.Values.res.kafka.entityOperator.topicOperator.limits.memory}}"
                requests:
                  cpu: "{{.Values.res.kafka.entityOperator.topicOperator.requests.cpu}}"
                  memory: "{{.Values.res.kafka.entityOperator.topicOperator.requests.memory}}"
            userOperator:
              resources:
                limits:
                  cpu: "{{.Values.res.kafka.entityOperator.userOperator.limits.cpu}}"
                  memory: "{{.Values.res.kafka.entityOperator.userOperator.limits.memory}}"
                requests:
                  cpu: "{{.Values.res.kafka.entityOperator.userOperator.requests.cpu}}"
                  memory: "{{.Values.res.kafka.entityOperator.userOperator.requests.memory}}"
    patchType: application/merge-patch+json
    targetObjectRef:
      apiVersion: base.automation.ibm.com/v1beta1
      kind: AutomationBase
      name: automationbase-sample
      namespace: {{.Values.aiManager.namespace}}
  serviceAccountRef:
    name: resource-locker-operator-controller-manager
