{{- if eq .Values.profile "x-small" }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: iaf-resource-locker
  namespace: resource-locker-operator
spec:
  patches:
  - id: automationbase-locker
    patchTemplate: |
      spec:
        kafka:
          entityOperator:
            tlsSidecar:
              resources:
                limits:
                  cpu: "{{.Values.res.kafka.entityOperator.tlsSidecar.limits.cpu}}"
                  memory: "{{.Values.res.kafka.entityOperator.tlsSidecar.limits.memory}}"
                requests:
                  cpu: "{{.Values.res.kafka.entityOperator.tlsSidecar.requests.cpu}}"
                  memory: "{{.Values.res.kafka.entityOperator.tlsSidecar.requests.memory}}"
            topicOperator:
              resources:
                limits:
                  cpu: "{{.Values.res.kafka.entityOperator.topicOperator.limits.cpu}}"
                  memory: "{{.Values.res.kafka.entityOperator.topicOperator.limits.memory}}"
                requests:
                  cpu: "{{.Values.res.kafka.entityOperator.topicOperator.requests.cpu}}"
                  memory: "{{.Values.res.kafka.entityOperator.topicOperator.requests.memory}}"
            userOperator:
              resources:
                limits:
                  cpu: "{{.Values.res.kafka.entityOperator.userOperator.limits.cpu}}"
                  memory: "{{.Values.res.kafka.entityOperator.userOperator.limits.memory}}"
                requests:
                  cpu: "{{.Values.res.kafka.entityOperator.userOperator.requests.cpu}}"
                  memory: "{{.Values.res.kafka.entityOperator.userOperator.requests.memory}}"
    patchType: application/merge-patch+json
    targetObjectRef:
      apiVersion: base.automation.ibm.com/v1beta1
      kind: AutomationBase
      name: automationbase-sample
      namespace: {{.Values.aiManager.namespace}}
  serviceAccountRef:
    name: resource-locker-operator-controller-manager
{{- end }}
