{{- if .Values.spec.aiManager.enabled }}
apiVersion: orchestrator.aiops.ibm.com/v1alpha1
kind: Installation
metadata:
  name: {{.Values.spec.aiManager.instanceName}}
  namespace: {{.Values.spec.aiManager.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "120"
spec:
  size: {{.Values.spec.aiManager.size}}
  storageClass: {{.Values.spec.storageClass}}
  storageClassLargeBlock: {{.Values.spec.storageClassLargeBlock}}
  imagePullSecret: ibm-entitlement-key
  license:
    accept: true
  pakModules:
  - name: aiopsFoundation
    enabled: true
  - name: applicationManager
    enabled: true
  - name: aiManager
    enabled: true
  - name: connection
    enabled: true
{{- end }}