{{- if .Values.spec.aiManager.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-aiops-orchestrator
  namespace: {{.Values.spec.aiManager.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "110"
spec:
  channel: {{.Values.spec.aiManager.channel}}
  installPlanApproval: Automatic
  name: ibm-aiops-orchestrator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
{{- end }}