{{- if or .Values.spec.eventManagerGateway.enabled .Values.spec.aiManager.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-operator-catalog
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  displayName: ibm-operator-catalog
  publisher: IBM Content
  sourceType: grpc
  image: {{.Values.spec.imageCatalog}}
  {{- if .Values.spec.eventManagerGateway.enabled }}
  updateStrategy:
    registryPoll:
      interval: 45m
  {{- end }}
{{- end }}