---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-argocd-admin-ai
  namespace: {{.Values.spec.aiManager.namespace}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-argocd-admin-ai
  annotations:
    argocd.argoproj.io/sync-wave: "20"
subjects:
  - kind: ServiceAccount
    name: openshift-argocd-admin-ai
    namespace: {{.Values.spec.aiManager.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin