---
apiVersion: batch/v1
kind: Job
metadata:
  name: cp4waiops-image-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "60"
  namespace: {{.Values.spec.aiManager.namespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |

              image_pull_secret=$(oc get secret ibm-entitlement-key -n {{.Values.spec.aiManager.namespace}} -o jsonpath={.metadata.name})

              if [[ "${image_pull_secret}" != ibm-entitlement-key ]]; then
                  oc create secret docker-registry ibm-entitlement-key \
                  --docker-username={{.Values.spec.dockerUsername}} \
                  --docker-password={{.Values.spec.dockerPassword}} \
                  --docker-server=cp.icr.io \
                  --namespace={{.Values.spec.aiManager.namespace}}
              fi

      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin-ai
  backoffLimit: 4