apiVersion: noi.ibm.com/v1beta1
kind: NOI
metadata:
  name: evtmanager
  namespace: {{.Values.spec.eventManager.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "120"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  license:
    accept: true
  advanced:
    antiAffinity: false
    imagePullPolicy: IfNotPresent
    imagePullRepository: cp.icr.io/cp/noi
  serviceContinuity:
    continuousAnalyticsCorrelation: false
    isBackupDeployment: false
  ldap:
    port: '3389'
    mode: standalone
    userFilter: 'uid=%s,ou=users'
    bindDN: 'cn=admin,dc=mycluster,dc=icp'
    sslPort: '3636'
    url: 'ldap://localhost:3389'
    suffix: 'dc=mycluster,dc=icp'
    groupFilter: 'cn=%s,ou=groups'
    baseDN: 'dc=mycluster,dc=icp'
    storageSize: 1Gi
    serverType: CUSTOM
    storageClass: ''
  backupRestore:
    enableAnalyticsBackups: false
  topology:
    storageClassElasticTopology: ''
    storageSizeElasticTopology: 75Gi
    storageSizeFileObserver: 5Gi
    storageClassFileObserver: ''
    iafCartridgeRequirementsName: ''
    appDisco:
      enabled: false
      scaleSSS: '1'
      tlsSecret: ''
      dbsecret: ''
      db2database: taddm
      dburl: ''
      certSecret: ''
      db2archuser: archuser
      secure: false
      scaleDS: '1'
      db2user: db2inst1
      dbport: '50000'
    observers:
      docker: false
      taddm: false
      servicenow: true
      ibmcloud: false
      alm: false
      contrail: false
      cienablueplanet: false
      kubernetes: true
      bigfixinventory: false
      junipercso: false
      dns: false
      itnm: false
      ansibleawx: false
      ciscoaci: false
      azure: false
      rancher: false
      newrelic: false
      vmvcenter: true
      rest: true
      appdynamics: false
      jenkins: false
      zabbix: false
      file: true
      googlecloud: false
      dynatrace: false
      aws: false
      openstack: false
      vmwarensx: false
    netDisco: false
  version: {{.Values.spec.eventManager.version}}
  entitlementSecret: ibm-entitlement-key
  clusterDomain: {{.Values.spec.eventManager.clusterDomain}}
  integrations:
    humio:
      repository: ''
      url: ''
  persistence:
    storageSizeNCOBackup: 5Gi
    enabled: false
    storageSizeNCOPrimary: 5Gi
    storageClassNCOPrimary: ''
    storageSizeImpactServer: 5Gi
    storageClassImpactServer: ''
    storageClassKafka: ''
    storageSizeKafka: 50Gi
    storageClassCassandraBackup: ''
    storageSizeCassandraBackup: 50Gi
    storageClassZookeeper: ''
    storageClassCouchdb: ''
    storageSizeZookeeper: 5Gi
    storageSizeCouchdb: 20Gi
    storageClassCassandraData: ''
    storageSizeCassandraData: 50Gi
    storageClassElastic: ''
    storageClassImpactGUI: ''
    storageSizeImpactGUI: 5Gi
    storageSizeElastic: 75Gi
    storageClassNCOBackup: ''
  deploymentType: {{.Values.spec.eventManager.deploymentType}}
