apiVersion: cloudpak.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: {{.Values.spec.providerConfigRef}}
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{.Values.spec.kubeConfigSecretNS}}
      name: {{.Values.spec.kubeConfigSecretName}}
      key: credentials

