apiVersion: cloudpak.crossplane.io/v1alpha1
kind: Cp4waiops
metadata:
  name: cp4waiops
spec:
  forProvider:
    catalogsource:
      image: {{.Values.spec.imageCatalog}}
      channel: {{.Values.spec.channel}}
    installParams:
      imagePullSecret: {{.Values.spec.imagePullSecret}}
      namespace: {{.Values.spec.cp4waiops_namespace}}
      license: 
        accept: true
      pakModules:
        - name: aiManager
          enabled: true
        - name: aiopsFoundation
          enabled: true
        - name: applicationManager
          enabled: true
          config: 
          - name: noi-operator
            spec: 
              noi:
                persistence:
                  storageClassDB2: rook-cephfs
      size: small
      storageClass: {{.Values.spec.storageClass}}
      storageClassLargeBlock: {{.Values.spec.storageClassLargeBlock}}
  providerConfigRef:
    name: {{.Values.spec.providerConfigRef}}