---
###################################
# CP4WAIOps - Common Configs
###################################
spec:

  ## AI Manager catalog source image
  ##
  imageCatalog: icr.io/cpopen/ibm-operator-catalog:latest

  ## dockerUsername is the usrname of IBM® Entitled Registry.
  ## It is used to create a docker-registry secret to enable your deployment to pull the AI Manager images 
  ## from the IBM® Entitled Registry.
  ## Default is cp
  # dockerUsername: cp

  ## Obtain the entitlement key that is assigned to your IBMid. 
  ## Log in to MyIBM Container Software Library: https://myibm.ibm.com/products-services/containerlibrary
  ## Opens in a new tab with the IBMid and password details 
  ## that are associated with the entitled software.
  ## DO NOT Commit your docker password here, but always specify it in UI or CLI when creating the ArgoCD app.
  ## 
  # dockerPassword: REPLACE_IT

  ## storageClass is the storage class that you want to use. 
  ## If the storage provider for your deployment is Red Hat OpenShift Data Foundation, 
  ## previously called Red Hat OpenShift Container Storage, then set this to ocs-storagecluster-cephfs
  ##
  storageClass: rook-cephfs

  ## If the storage provider for your deployment is Red Hat OpenShift Data Foundation, 
  ## previously called Red Hat OpenShift Container Storage, then set this to ocs-storagecluster-ceph-rbd
  storageClassLargeBlock: rook-cephfs

  eventManager:

    # eventManager version
    version: 1.6.6

    ## Use the fully qualified domain name (FQDN) to formulate the clusterDomain property, using the following formula:
    ##
    clusterDomain: apps.clustername.*.*.com

    ## A channel defines a stream of updates for an Operator and is used to roll out updates for subscribers. 
    ## For example, if you want to install Evemt Manager 1.5, the channel should be v1.5
    ##
    channel: v1.10

    ## Deployment type (trial or production)
    ## 
    deploymentType: trial

    ## namespace is the project (namespace) that you want to create the Event Manager instance in.
    ## You must create a custom project (namespace) and not use the default, kube-system,
    ## kube-public, openshift-node, openshift-infra, or openshift projects (namespaces). 
    ##
    namespace: noi
