apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: crossplane
    meta.helm.sh/release-namespace: crossplane-system
  labels:
    app: crossplane
    app.kubernetes.io/managed-by: Helm
    chart: crossplane-1.2.1
    heritage: Helm
    release: crossplane
  name: upbound-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin 
subjects:
- kind: ServiceAccount
  name: crossplane
  namespace: upbound-system
