apiVersion: roks.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: ibmcloud-connect-credentials
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: roks-provider-secret
      key: credentials
