{{- if hasPrefix "x-small" .Values.cp4waiops.profile }} 
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: resource-lockers
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{ `{{name}}-resource-locker` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "100"
    spec:
      destination:
        namespace: resource-locker-operator
        server: '{{ `{{server}}` }}'
      project: default
      source:
        chart: resource-locker-operator
        repoURL: https://redhat-cop.github.io/resource-locker-operator
        targetRevision: v1.1.3
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
{{- end }}

