{{- if .Values.cp4waiops.aiManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4waiops-aimanagers
spec:
  generators:
  {{- if .Values.argocd.allowLocalDeploy }}
  - clusters: {}
  {{- else }}
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  {{- end }}
  template:
    metadata:
      name: '{{ `{{name}}-cp4waiops-aimanager` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "200"
    spec:
      destination:
        namespace: '{{ .Values.cp4waiops.aiManager.namespace }}'
        server: '{{ `{{server}}` }}'
      project: default
      source:
        path: "config/cp4waiops/install-aimgr"
        repoURL: {{ default "https://github.com/IBM/cp4waiops-gitops" .Values.cp4waiops.repoURL }}
        targetRevision: {{ default "release-3.6" .Values.cp4waiops.targetRevision }}
        helm:
          parameters:
            - name: spec.aiManager.instanceName
              value: '{{ .Values.cp4waiops.aiManager.instanceName }}'
            - name: spec.aiManager.namespace
              value: '{{ .Values.cp4waiops.aiManager.namespace }}'
            {{- if hasPrefix "x-small" .Values.cp4waiops.profile }}
            - name: spec.aiManager.size
              value: 'small'
            {{- else }}
            - name: spec.aiManager.size
              value: '{{ .Values.cp4waiops.profile }}'
            {{- end }}
            {{- if .Values.cp4waiops.imageCatalog }}
            - name: spec.imageCatalog
              value: '{{ .Values.cp4waiops.imageCatalog }}'
            {{- end }}
            {{- if .Values.cp4waiops.aiManager.channel }}
            - name: spec.aiManager.channel
              value: '{{ .Values.cp4waiops.aiManager.channel }}'
            {{- end }}
            {{- if .Values.cp4waiops.isSNO}}
            - name: spec.isSNO
              value: '{{ .Values.cp4waiops.isSNO }}'
            {{- end }}
            {{- if .Values.cp4waiops.storageClass }}
            - name: spec.storageClass
              value: '{{ .Values.cp4waiops.storageClass }}'
            {{- end }}
            {{- if .Values.cp4waiops.storageClassLargeBlock }}
            - name: spec.storageClassLargeBlock
              value: '{{ .Values.cp4waiops.storageClassLargeBlock }}'
            {{- end }}
            {{- if .Values.globalImagePullSecrets }}
            {{- range $idx, $cfg := .Values.globalImagePullSecrets }}
            {{- range $key, $val := $cfg }}
            - name: globalImagePullSecrets[{{ $idx }}].{{ $key }}
              value: '{{ $val }}'
            {{- end }}
            {{- end }}
            {{- end }}
      ignoreDifferences:
        - group: orchestrator.aiops.ibm.com
          jsonPointers:
            - /spec/pakModules
          kind: Installation
        - group: apiextensions.k8s.io
          jsonPointers:
            - /metadata/generation
          kind: CustomResourceDefinition
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
{{- end }}
