{{- if .Values.cluster }}
{{- if and .Values.cluster.enabled (eq .Values.cluster.provider.type "fyre") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-operator-fyre
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    {{- if .Values.argocd.namespace }}
    namespace: {{ .Values.argocd.namespace }}
    {{- else if eq .Values.argocd.cluster "kubernetes" }}
    namespace: argocd
    {{- else if eq .Values.argocd.cluster "openshift" }}
    namespace: openshift-gitops
    {{- end }}
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops-charts/cluster-operator-fyre
    repoURL: https://github.com/IBM/sample-app-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
{{- end }}
