apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp-shared
spec:
  generators:
  {{- if .Values.argocd.allowLocalDeploy }}
  - clusters: {}
  {{- else }}
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  {{- end }}
  template:
    metadata:
      name: '{{ `{{name}}-cp-shared` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "110"    
    spec:
      destination:
        namespace: openshift-marketplace
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: config/cp-shared/operators
        repoURL: {{ default "https://github.com/IBM/cp4waiops-gitops" .Values.cp4waiops.repoURL }}
        targetRevision: {{ default "release-3.6" .Values.cp4waiops.targetRevision }}
        helm:
          parameters:
            {{- if .Values.cp4waiops.imageCatalog }}
            - name: spec.imageCatalog
              value: '{{ .Values.cp4waiops.imageCatalog }}'
            {{- end }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
