apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp-shared
  annotations:
    argocd.argoproj.io/sync-wave: "110"
spec:
  destination:
    namespace: openshift-marketplace
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: config/cp-shared
    repoURL: https://github.com/IBM/cp4waiops-gitops
    targetRevision: release-3.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
