{{- if .Values.cp4waiops.eventManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4waiops-eventmanagers
spec:
  generators:
  {{- if .Values.argocd.allowLocalDeploy }}
  - clusters: {}
  {{- else }}
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  {{- end }}
  template:
    metadata:
      name: '{{ `{{name}}-cp4waiops-eventmanager` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "200"
    spec:
      destination:
        namespace: '{{ .Values.cp4waiops.eventManager.namespace }}'
        server: '{{ `{{server}}` }}'
      project: default
      source:
        path: "config/cp4waiops/install-emgr"
        repoURL: {{ default "https://github.com/IBM/cp4waiops-gitops" .Values.cp4waiops.repoURL }}
        targetRevision: {{ default "release-3.6" .Values.cp4waiops.targetRevision }}
        helm:
          parameters:
            - name: spec.eventManager.namespace
              value: '{{ .Values.cp4waiops.eventManager.namespace }}'
            - name: spec.eventManager.clusterDomain
              value: '{{ .Values.cp4waiops.eventManager.clusterDomain }}'
            {{- if .Values.cp4waiops.eventManager.version }}
            - name: spec.eventManager.version
              value: '{{ .Values.cp4waiops.eventManager.version }}'
            {{- end }}      
            {{- if .Values.cp4waiops.eventManager.channel }}
            - name: spec.eventManager.channel
              value: '{{ .Values.cp4waiops.eventManager.channel }}'
            {{- end }}
            {{- if .Values.cp4waiops.eventManager.deploymentType }}
            - name: spec.eventManager.deploymentType
              value: '{{ .Values.cp4waiops.eventManager.deploymentType }}'
            {{- end }}
            {{- if .Values.cp4waiops.eventManager.imageCatalog }}
            - name: spec.imageCatalog
              value: '{{ .Values.cp4waiops.eventManager.imageCatalog }}'
            {{- end }}
            {{- if .Values.cp4waiops.storageClass }}
            - name: spec.storageClass
              value: '{{ .Values.cp4waiops.storageClass }}'
            {{- end }}
            {{- if .Values.cp4waiops.storageClassLargeBlock }}
            - name: spec.storageClassLargeBlock
              value: '{{ .Values.cp4waiops.storageClassLargeBlock }}'
            {{- end }}
            {{- if .Values.globalImagePullSecrets }}
            {{- range $idx, $cfg := .Values.globalImagePullSecrets }}
            {{- range $key, $val := $cfg }}
            - name: globalImagePullSecrets[{{ $idx }}].{{ $key }}
              value: '{{ $val }}'
            {{- end }}
            {{- end }}
            {{- end }}
      ignoreDifferences:
        - group: noi.ibm.com/v1beta1
          jsonPointers:
            - /spec
          kind: NOI
        - group: v1
          jsonPointers:
            - /imagePullSecrets
          kind: ServiceAccount
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
{{- end }}
