{{- if .Values.humio }}
{{- if .Values.humio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: humio-loggings
spec:
  generators:
  {{- if .Values.argocd.allowLocalDeploy }}
  - clusters: {}
  {{- else }}
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  {{- end }}
  template:
    metadata:
      name: '{{ `{{name}}-humio-logging` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "200"
    spec:
      destination:
        namespace: humio-logging
        server: '{{ `{{server}}` }}'
      project: default
      source:
        path: gitops-charts/humio-helm-charts
        repoURL: https://github.com/IBM/sample-app-gitops
        targetRevision: HEAD
        helm:
          parameters:
            - name: humio-core.openshift.host
              value: 'true'
            - name: humio-fluentbit.humioReleaseName
              value: '{{ `{{name}}-humio-logging` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=false
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
{{- end }}
{{- end }}
