{{- if .Values.istio }}
{{- if .Values.istio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istios
spec:
  generators:
  {{- if .Values.argocd.allowLocalDeploy }}
  - clusters: {}
  {{- else }}
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  {{- end }}
  template:
    metadata:
      name: '{{ `{{name}}-istio` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "200"
    spec:
      destination:
        namespace: istio-system
        server: '{{ `{{server}}` }}'
      project: default
      source:
        path: gitops-charts/istio
        repoURL: https://github.com/IBM/sample-app-gitops
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=false
          - SkipDryRunOnMissingResource=true
          - FailOnSharedResource=true
          - CreateNamespace=true
{{- end }}
{{- end }}
