{{- $resource_locker_enabled := false -}}

{{- if .Values.robotshop }}
  {{- if .Values.robotshop.enabled }}
    {{- $resource_locker_enabled = true -}}
  {{- end }}
{{- end }}

{{- if .Values.humio }}
  {{- if .Values.humio.enabled }}
    {{- $resource_locker_enabled = true -}}
  {{- end }}
{{- end }}

{{- if hasPrefix "x-small" .Values.cp4waiops.profile }}
  {{- $resource_locker_enabled = true -}}
{{- end }}

{{- if $resource_locker_enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: resource-lockers
spec:
  generators:
  {{- if .Values.argocd.allowLocalDeploy }}
  - clusters: {}
  {{- else }}
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  {{- end }}
  template:
    metadata:
      name: '{{ `{{name}}-resource-locker` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "100"
    spec:
      destination:
        namespace: resource-locker-operator
        server: '{{ `{{server}}` }}'
      project: default
      source:
        chart: resource-locker-operator
        repoURL: https://redhat-cop.github.io/resource-locker-operator
        targetRevision: v1.1.3
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
{{- end }}
