apiVersion: instana.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: instana-provider-config 
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: k8s-kubeconfig 
      key: credentials
