{{- if or .Values.spec.eventManagerGateway.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cp4waiops-image-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: ""
  namespace: {{.Values.spec.cp4waiops_namespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "64Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |
              set -eo pipefail
              set -x

              image_pull_secret=$(oc get secret target-registry-secret -n {{.Values.spec.cp4waiops_namespace}} -o jsonpath={.metadata.name}) \
              || {
                  echo "Image pull secret target-registry-secret not exist."
              }

              if [[ "${image_pull_secret}" != target-registry-secret ]]; then
                  oc create secret docker-registry target-registry-secret \
                  --docker-username={{.Values.spec.localDockerRegistryUser}} \
                  --docker-password={{.Values.spec.localDockerRegistryPassword}} \
                  --docker-server={{.Values.spec.localDockerRegistryHost}}:{{.Values.spec.localDockerRegistryPort}} \
                  --namespace={{.Values.spec.cp4waiops_namespace}}
              fi

      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin
  backoffLimit: 4
{{- end }}