{{- if .Values.spec.eventManagerGateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: noi-service-account
  namespace: {{.Values.spec.cp4waiops_namespace}}
imagePullSecrets:
- name: target-registry-secret
{{- end }}