{{- if or .Values.spec.eventManagerGateway.enabled .Values.spec.aiManager.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: aiops-operator-group
  namespace: {{.Values.spec.cp4waiops_namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - {{.Values.spec.cp4waiops_namespace}}
{{- end }}